// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEntries(arg1) {
  return window['go']['main']['App']['DeleteEntries'](arg1);
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}

export function UndoLastCleanup() {
  return window['go']['main']['App']['UndoLastCleanup']();
}
