// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {trayicons} from '../models';

export function DeleteEntries(arg1:Array<string>):Promise<main.DeleteResult>;

export function Scan():Promise<Array<trayicons.TrayIconEntry>>;

export function UndoLastCleanup():Promise<main.DeleteResult>;
